name: Bug Report
description: Report a bug in xUI
title: 'bug(COMPONENT): TITLE'
labels: ['needs triage']
body:
  - type: checkboxes
    id: is-regression
    attributes:
      label: Is this a regression?
      description: Did this behavior used to work in the previous version?
      options:
        - label: Yes, this behavior used to work in the previous version
  - type: input
    id: version-bug-was-not-present
    attributes:
      label: The previous version in which this bug was not present was
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Use StackBlitz to reproduce your issue:
        - [xUI StackBlitz starter](https://stackblitz.com/fork/xui)

        Issues that do not include a StackBlitz (or other REPL) reproduction link will be closed.
        If it is not possible to create a StackBlitz reproduction for your issue, please explain why
        and include any other information you can to help the team reliably reproduce the issue.
      value: |
        StackBlitz link:
        Steps to reproduce:
        1.
        2.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What behavior were you expecting to see?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What behavior did you actually see?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: You can use `ng version` command.
      value: |
        - Angular:
        - xUI:
        - Browser(s):
        - Operating System (e.g. Windows, macOS, Ubuntu):
    validations:
      required: true
