name: Documentation
description: Suggest an improvement to our documentation at xuijs.org
title: 'docs-bug(COMPONENT): TITLE'
labels: ['docs', 'needs triage']
body:
  - type: textarea
    id: description
    attributes:
      label: Documentation Feedback
      description: |
        Provide a brief summary of what you would like to see changed in our documentation at [xuijs.org](https://xuijs.org/).
        Feel free to provide any suggestions of content or examples you’d like us to include.
    validations:
      required: true
  - type: input
    id: affected-documentation-page
    attributes:
      label: Affected documentation page
      description: Insert a link to the affected page on [xuijs.org](https://xuijs.org/).
    validations:
      required: true
