name: Continuous Delivery

on:
  push:
    branches:
      - master
      - develop

env:
  HUSKY: 0

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest

    permissions:
      packages: read
      id-token: write
      contents: write

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Release
        run: yarn semantic-release
